### ISSUE TITLE
can't use actix-web-prom with actix-web 4

### ISSUE THREAD

**Issue by abdelmonem17** [nlopes/actix-web-prom#56]
hello everyone I am tring to use use actix-web-prom with actix-web 4 whith the below dependency

> actix-web = {git = "https://github.com/actix/actix-web",version ="4.0.0-beta.8"}
> actix-web-prom = { git = "https://github.com/arthurlm/actix-web-prom.git", branch = "actix-next" }

but I got the following error 

> not all trait items implemented, missing: `Error`
>    --> C:\Users\AbdelmonemMohamed\.cargo\git\checkouts\actix-web-prom-af77977b77662c26\a23d5a6\src\lib.rs:589:1
>     |
> 589 | impl<B: MessageBody> MessageBody for StreamLog<B> {
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Error` in implementation
>     |
>     = help: implement the missing item: `type Error = Type;`

please any help

**Comment by arthurlm** [comment]
Hi,

I have synchronize branch names in my repository following branch name in `actix-web` repository.
So you should try setting your `Cargo.toml` as bellow:

```toml
actix-web = "4.0.0-beta.8"
actix-web-prom = { git = "https://github.com/arthurlm/actix-web-prom.git", branch = "actix-web-4.0.0-beta8" }
```

Indeed comment in issue #51 is a little bit outdated.
